# Generated by Django 2.2.3 on 2019-07-23 02:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20190723_1141'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Post',
        ),
    ]
