# Generated by Django 2.2.3 on 2019-07-23 03:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20190723_1158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Profile',
        ),
    ]
